from enum import Enum
from typing import List
from abc import ABC, abstractmethod

# Define user roles
class UserRole(Enum):
    ADMIN = "Admin"
    MANAGER = "Manager"
    STAFF = "Staff"


# Username, Role, Permission
class User(ABC):
    def __init__(self, username: str, role: UserRole):
        self._username = username
        self._role = role

    # Get username
    def get_username(self):
        return self._username

    # Get role
    def get_role(self):
        return self._role

    # Detemine whether the current user has the right to perform a certain operation
    def can_perform_action(self, action: str) -> bool:
        permissions = {
            UserRole.ADMIN: ["add", "remove", "update", "view", "report"],
            UserRole.MANAGER: ["update", "view", "report"],
            UserRole.STAFF: ["view"]
        }
        return action in permissions.get(self._role, [])
    
    # Abstract method: any subclass must implement its own report generation
    @abstractmethod
    def generate_full_report(self, inventory) -> str:
        pass
    
    def __str__(self):
        return f"User: {self._username}, Role: {self._role.value}"

# Administrator(default role ---> Admin)
class AdminUser(User):
    def __init__(self, username: str):
        super().__init__(username, UserRole.ADMIN)

    # Generate a complete inventory report
    def generate_full_report(self, inventory) -> str:
        report = f"=== Full Inventory Report (Generated by {self.get_username()}) ===\n"
        report += str(inventory) + "\n"
        for product in inventory.list_all_products():
            report += str(product) + "\n"
        report += f"Total Inventory Value: ${inventory.calculate_total_value():.2f}\n"
        return report
