import tkinter as tk
from tkinter import ttk, messagebox
from user import UserRole, AdminUser, User
from typing import Optional

# user database
USER_CREDENTIALS = {
    "admin": {"password": "admin123", "role": UserRole.ADMIN},
    "manager": {"password": "manager123", "role": UserRole.MANAGER},
    "staff": {"password": "staff123", "role": UserRole.STAFF}
}

# User class (Manager and Staff)
class ManagerUser(User):
    def __init__(self, username: str):
        super().__init__(username, UserRole.MANAGER)
    
    def generate_full_report(self, inventory) -> str:
        report = f"=== Manager Inventory Report (Generated by {self.get_username()}) ===\n"
        report += str(inventory) + "\n"
        for product in inventory.list_all_products():
            report += str(product) + "\n"
        report += f"Total Inventory Value: ${inventory.calculate_total_value():.2f}\n"
        return report

class StaffUser(User):
    def __init__(self, username: str):
        super().__init__(username, UserRole.STAFF)
    
    def generate_full_report(self, inventory) -> str:
        report = f"=== Staff Inventory Report (Generated by {self.get_username()}) ===\n"
        report += str(inventory) + "\n"
        for product in inventory.list_all_products():
            report += str(product) + "\n"
        return report

class LoginGUI:
    def __init__(self, root):
        self.root = root
        self.root.title("Inventory System - Login")
        self.root.geometry("450x350")
        self.root.resizable(False, False)
        
        # store the user boject
        self.logged_in_user: Optional[User] = None
        
        # UI
        self.create_login_ui()

    def create_login_ui(self):
        # main
        main_frame = ttk.Frame(self.root, padding="30 20 30 30")
        main_frame.pack(fill=tk.BOTH, expand=True)
        
        # title
        title_label = ttk.Label(main_frame, text="Inventory Management System", font=("Arial", 16, "bold"))
        title_label.pack(pady=(0, 20))
        
        # structure
        username_frame = ttk.Frame(main_frame)
        username_frame.pack(fill=tk.X, pady=5)
        ttk.Label(username_frame, text="Username:", font=("Arial", 10)).pack(side=tk.LEFT)
        self.username_entry = ttk.Entry(username_frame, font=("Arial", 10))
        self.username_entry.pack(side=tk.RIGHT, fill=tk.X, expand=True)
        # ID tips
        self.username_hint = ttk.Label(main_frame, text="(Admin: admin | Manager: manager | Staff: staff)", 
                                       font=("Arial", 8), foreground="gray")
        self.username_hint.pack(anchor=tk.W, padx=2, pady=(0, 10))
        
        # password structure
        password_frame = ttk.Frame(main_frame)
        password_frame.pack(fill=tk.X, pady=5)
        ttk.Label(password_frame, text="Password:", font=("Arial", 10)).pack(side=tk.LEFT)
        self.password_entry = ttk.Entry(password_frame, show="*", font=("Arial", 10))
        self.password_entry.pack(side=tk.RIGHT, fill=tk.X, expand=True)
        # password tips
        self.password_hint = ttk.Label(main_frame, text="(Default password for all: xxx123, e.g. admin123)", 
                                       font=("Arial", 8), foreground="gray")
        self.password_hint.pack(anchor=tk.W, padx=2, pady=(0, 20))
        
        # login button
        login_btn = ttk.Button(main_frame, text="Login", command=self.validate_login, style="Accent.TButton")
        login_btn.pack(fill=tk.X, pady=10)
        
        # ui
        self.style_login_ui()

    def style_login_ui(self):
        # create style
        style = ttk.Style()
        style.configure("Accent.TButton", font=("Arial", 10, "bold"))
        style.configure("TLabel", font=("Arial", 10))
        style.configure("TEntry", font=("Arial", 10))
        
        # set background 
        self.root.configure(bg="#f0f0f0")
        main_frame = self.root.winfo_children()[0]
        main_frame.configure(style="Main.TFrame")
        style.configure("Main.TFrame", background="#f0f0f0")

    def validate_login(self):
        
        username = self.username_entry.get().strip()
        password = self.password_entry.get().strip()
        
        # check blank
        if not username or not password:
            messagebox.showerror("Error", "Username and Password cannot be empty!")
            return
        
        # check message
        user_data = USER_CREDENTIALS.get(username)
        if not user_data or user_data["password"] != password:
            messagebox.showerror("Error", "Invalid username or password!")
            return
        
        # create user object
        if user_data["role"] == UserRole.ADMIN:
            self.logged_in_user = AdminUser(username)
        elif user_data["role"] == UserRole.MANAGER:
            self.logged_in_user = ManagerUser(username)
        elif user_data["role"] == UserRole.STAFF:
            self.logged_in_user = StaffUser(username)
        
        # close login page
        messagebox.showinfo("Success", f"Welcome {username}! (Role: {user_data['role'].value})")
        self.root.destroy()

def show_login_window() -> Optional[User]:
    
    login_root = tk.Tk()
    login_app = LoginGUI(login_root)
    login_root.mainloop()
    return login_app.logged_in_user